### ISSUE TITLE
master-vue branch mvn clean install error

### ISSUE THREAD

**Issue by xuzhipeng1028** [somowhere/albedo#24]
albedo-boot-redis-lock pom.xml parent does not exist
```
<parent>

<artifactId>ua-loan-plugins</artifactId>

<groupId>com.zhph.java</groupId>

<version>1.0.0-SNAPSHOT</version>

</parent>
```
![image](https://user-images.githubusercontent.com/34650249/47707160-1280b580-dc66-11e8-8eb8-612593a218d1.png)

**Comment by xuzhipeng1028** [comment]
<parent>
        <artifactId>albedo-boot-plugins</artifactId>
        <groupId>com.albedo.java</groupId>
        <version>1.3.0-SNAPSHOT</version>
    </parent>

**Comment by somowhere** [comment]
solve in 2.0
