### ISSUE TITLE
master-vue branch mvn clean install FileNotFoundException

### ISSUE THREAD

**Issue by xuzhipeng1028** [somowhere/albedo#25]
albedo-boot-common /util/config/SystemConfig.java global.properties does not exist
![image](https://user-images.githubusercontent.com/34650249/47707727-81aad980-dc67-11e8-8130-910eb2412180.png)
![image](https://user-images.githubusercontent.com/34650249/47707871-d5b5be00-dc67-11e8-8b70-19ff44df641e.png)

**Comment by somowhere** [comment]
solve in 2.0
