### ISSUE TITLE
新版本sql语句内的别名group和sql关键字group冲突报错了

### ISSUE THREAD

**Issue by GeniusShiki** [somowhere/albedo#29]
新版本sql语句内的别名group和sql关键字group冲突报错了。
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group,job_status AS jobStatus,cron_expression AS cronExpression,bean_class AS be' at line 1; 
bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group,job_status AS jobStatus,cron_expression AS cronExpression,bean_class AS be' at line 1

**Comment by somowhere** [comment]
solve in 2.0
