### ISSUE TITLE
代码生成器的模板(viewIndex.xml)问题

### ISSUE THREAD

**Issue by wanghuyin** [somowhere/albedo#32]
![代码生成器](https://user-images.githubusercontent.com/29270852/70978760-51ccc880-20eb-11ea-9e81-24d64f70489d.png)
viewIndex.xml 文件第 77 ,206,214行 listQuery.page 应改为 listQuery.current ,否则不能与mybatis Plus 的分页插件配合完成分页查询.

**Comment by somowhere** [comment]
已经修改
