### ISSUE TITLE
功能权限没问题，数据权限怎么区分

### ISSUE THREAD

**Issue by EpicWang** [somowhere/albedo#35]
比如管理员可以看所有订单，个人用户只能看自己的订单

**Comment by somowhere** [comment]
数据权限是 [DataScopeInterceptor](https://github.com/somowhere/albedo/blob/master/albedo-plugins/albedo-data-mybatis/src/main/java/com/albedo/java/common/persistence/datascope/DataScopeInterceptor.java) 实现，建议参考com.albedo.java.modules.sys.web.UserResource#findPage 用户管理分页
